### ISSUE TITLE
Great App

### ISSUE THREAD

**Issue by ImTryingToLearnStuff** [nebhead/spkr-select#2]
Thanks for this APP, exactly what I was looking for.  I am trying to integrate this with HA using the REST API but can not connect using the URL provided.  `Example URL: https://hostname:34534/extapi/xxxxxxxxxxxxxxxxx`  When I include the port `34534` I get a `ERR_CONNECTION_REFUSED` response, and removing the port number, using the default port for https (443) I get a `404 error`.  
`

**Comment by nebhead** [comment]
Hey @ImTryingToLearnStuff!  Glad this is going to work for you.  OK, so first, that example URL is for external access (i.e. outside of your network) and it is purely an example.  If you are trying to have something from inside your network access your speaker selector, you'll just want to use http://your.ip.address.here/api.  But regardless of all of that, I have a significantly upgraded version of this project here: https://github.com/nebhead/spkr-select-v3 and documentation here: https://nebhead.github.io/spkr-select-v3/  In the upgraded project I have some rudimentary yaml for connecting your Home Assistant to the speaker selector (https://nebhead.github.io/spkr-select-v3/ha).  This new version should work with the older hardware.   Let me know if you have any other questions!  Good luck! (btw, I will be away from the computer most of the day today, but will be back tomorrow)

**Comment by ImTryingToLearnStuff** [comment]
Thanks for the fast response, I updated to v3 and was able to get the API to work in HA.  I did have to change `is_on_template: ""` in your example to `is_on_template: '{{ value_json.spkr_00 == "on"}}'` or the switch would toggle back to off automatically.     

I Created a few different buttons that look nice with my current layout.  

![image](https://user-images.githubusercontent.com/90283383/150783773-497c8465-e2ad-4e48-9bdd-862c27b9ca6f.png)

![image](https://user-images.githubusercontent.com/90283383/150783817-5240142e-cc1e-4816-8e7d-25e7aa6291be.png)

Thanks again for sharing this project, the HA integration makes it much more useful then my previous stand alone app.

**Comment by nebhead** [comment]
That looks amazing!!  Really nice job!  Could you share your yaml so that I can possibly integrate it into the instructions for this project?  I really like the button layout you have.

**Comment by ImTryingToLearnStuff** [comment]
Happy to share the button layouts.  This card uses a `custom:button-card` I installed this using `HACS` 

![image](https://user-images.githubusercontent.com/90283383/150877571-9a196b4e-c06c-47af-9831-1b320373f500.png)

```
type: vertical-stack
panel: true
cards:
  - type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: switch.family_room_speakers
        hold_action:
          action: more-info
        tap_action:
          action: toggle
        icon: mdi:volume-mute
        name: Family Room
        state:
          - styles:
              card:
                - border: 'solid 1px #fbff00'
                - box-shadow: '0px 0px 10px 3px #fbff00'
              label:
                - color: var(--paper-item-icon-active-color)
            icon: mdi:volume-high
            value: 'on'
      - type: custom:button-card
        entity: switch.kitchen_speakers
        hold_action:
          action: more-info
        tap_action:
          action: toggle
        icon: mdi:volume-mute
        name: Kitchen
        state:
          - styles:
              card:
                - border: 'solid 1px #fbff00'
                - box-shadow: '0px 0px 10px 3px #fbff00'
              label:
                - color: var(--paper-item-icon-active-color)
            icon: mdi:volume-high
            value: 'on'
      - type: custom:button-card
        entity: switch.living_room_speakers
        hold_action:
          action: more-info
        tap_action:
          action: toggle
        icon: mdi:volume-mute
        name: Living Room
        state:
          - styles:
              card:
                - border: 'solid 1px #fbff00'
                - box-shadow: '0px 0px 10px 3px #fbff00'
              label:
                - color: var(--paper-item-icon-active-color)
            icon: mdi:volume-high
            value: 'on'
```

**Comment by nebhead** [comment]
Thank you!!  I'll definitely play with this on my HA setup.

**Comment by ImTryingToLearnStuff** [comment]
The second card:

![image](https://user-images.githubusercontent.com/90283383/150879529-fbd2bfba-742e-4bdf-9fe2-85c1fc88404f.png)

uses a template called `speaker_button` the template gets added to the `Raw Configuration editor` for the dashboard.

```
  speaker_button:
    aspect_ratio: 4/3
    color_type: icon
    hold_action:
      action: more-info
      haptic: selection
    label: >
      [[[ var bri = entity.attributes.brightness &&
      Math.round(entity.attributes.brightness / 2.55);  if
        (entity.state === 'on') return (bri ? (bri+"%") : 'On'); else return "Off"; ]]]
    layout: icon_label
    show_label: true
    show_name: true
    state:
      - styles:
          card:
            - border: 'solid 1px #fbff00'
            - box-shadow: '0px 0px 10px 3px #fbff00'
          label:
            - color: var(--paper-item-icon-active-color)
        value: 'on'
        icon: mdi:volume-high
      - styles:
          card:
            - border: solid 1px var(--primary-color)
            - box-shadow: none
        value: 'off'
        icon: mdi:volume-mute
      - icon: mdi:alert
        label: Lost
        styles:
          card:
            - border: 'solid 1px #7f7f7f'
            - box-shadow: none
          icon:
            - color: '#ff0000'
            - opacity: 0.4
          label:
            - color: '#7f7f7f'
          name:
            - color: '#7f7f7f'
        value: unavailable
    styles:
      card:
        - border-radius: 10px
        - padding: 6px 6px 6px 6px
        - margin: 0% 0% 0% 0%
        - '--ha-card-background': rgba(0, 0, 0, 0)
      grid:
        - grid-template-areas: '"i l l" "n n n"'
        - grid-template-rows: 33% auto
        - grid-template-columns: 33% auto
      icon:
        - width: 28px
        - padding: 0px 0px 0px 0px
        - color: var(--button-card-light-color-no-temperature)
      label:
        - font-size: 12px
        - justify-self: right
        - padding: 0px 0px 0px 0px
        - color: var(--secondary-text-color)
      name:
        - justify-self: middle
        - align-self: end
        - font-size: 14px
        - padding: 0px 0px 0px 0px
        - color: var(--primary-text-color)
        - white-space: normal
    tap_action:
      action: toggle
```
You will also need to install the `custom:hui-element`, I did this using HACS.

Once the template, and `custom:hui-element` are in place use the Entities card with the following configuration....

```
entities:
  - card_type: horizontal-stack
    cards:
      - entity: switch.family_room_speakers
        name: Family Room
        icon: mdi:volume-high
        template: speaker_button
        type: custom:button-card
      - entity: switch.kitchen_speakers
        name: Kitchen
        icon: mdi:volume-high
        template: speaker_button
        type: custom:button-card
      - entity: switch.living_room_speakers
        name: Living Room
        icon: mdi:volume-high
        template: speaker_button
        type: custom:button-card
    type: custom:hui-element
show_header_toggle: false
type: entities
title: Speaker Controls
```
